 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/money", type: :request do
  
  # Money. As you add validations to Money, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Money.create! valid_attributes
      get money_index_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      money = Money.create! valid_attributes
      get money_url(money)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_money_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      money = Money.create! valid_attributes
      get edit_money_url(money)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Money" do
        expect {
          post money_index_url, params: { money: valid_attributes }
        }.to change(Money, :count).by(1)
      end

      it "redirects to the created money" do
        post money_index_url, params: { money: valid_attributes }
        expect(response).to redirect_to(money_url(Money.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Money" do
        expect {
          post money_index_url, params: { money: invalid_attributes }
        }.to change(Money, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post money_index_url, params: { money: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested money" do
        money = Money.create! valid_attributes
        patch money_url(money), params: { money: new_attributes }
        money.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the money" do
        money = Money.create! valid_attributes
        patch money_url(money), params: { money: new_attributes }
        money.reload
        expect(response).to redirect_to(money_url(money))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        money = Money.create! valid_attributes
        patch money_url(money), params: { money: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested money" do
      money = Money.create! valid_attributes
      expect {
        delete money_url(money)
      }.to change(Money, :count).by(-1)
    end

    it "redirects to the money list" do
      money = Money.create! valid_attributes
      delete money_url(money)
      expect(response).to redirect_to(money_index_url)
    end
  end
end
